### ISSUE TITLE
运行一会儿就报错，能否支持下koishi不带浏览器核心的lite版的，省些内存

### ISSUE THREAD

**Issue by samcaicn** [saurlax/koishi-plugin-maxkb#2]
Error: Internal Server Error
                            at [cordis.invoke] (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:340:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Proxy.<anonymous> (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:184:26)
                            at async chat (/koishi/node_modules/koishi-plugin-maxkb/lib/index.js:50:15)
                            at async Proxy.<anonymous> (/koishi/node_modules/koishi-plugin-maxkb/lib/index.js:74:20)
2024-10-31 19:26:46 [W] app Error: Parse Error: Invalid status code
                            at AxiosError.from (/koishi/node_modules/axios/dist/node/axios.cjs:876:14)
                            at RedirectableRequest.handleRequestError (/koishi/node_modules/axios/dist/node/axios.cjs:3156:25)
                            at RedirectableRequest.emit (node:events:531:35)
                            at RedirectableRequest.emit (node:domain:488:12)
                            at eventHandlers.<computed> (/koishi/node_modules/follow-redirects/index.js:49:24)
                            at ClientRequest.emit (node:events:519:28)
                            at ClientRequest.emit (node:domain:488:12)
                            at TLSSocket.socketOnData (node:_http_client:549:9)
                            at TLSSocket.emit (node:events:519:28)
                            at TLSSocket.emit (node:domain:488:12)
                            at addChunk (node:internal/streams/readable:559:12)
                            at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
                            at Readable.push (node:internal/streams/readable:390:5)
                            at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)
                            at Axios.request (/koishi/node_modules/axios/dist/node/axios.cjs:4287:41)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by samcaicn** [comment]
应该是图片异常没有处理

**Comment by samcaicn** [comment]
REGEX:(?insx)/[^?/]*.(css|ico|jpg|png|gif|bmp|wav)(?.*)?$

**Comment by saurlax** [comment]
这个是向 MaxKB API 发送 chat 请求的时候出错了，可能是因为 MaxKB 服务端有问题或者是网络问题
